SELECT SYSDATE FROM DUAL;

CREATE TABLE TBL_USER(
	USER_NUMBER NUMBER,
	USER_ID VARCHAR2(10),
	USER_PW VARCHAR2(20),
	USER_NAME VARCHAR2(100),
	USER_AGE NUMBER,
	USER_GENDER CHAR(1),
	CONSTRAINT USER_PK PRIMARY KEY (USER_NUMBER)
);

CREATE SEQUENCE SEQ_USER;

SELECT * FROM TBL_USER;